datasets:
  - "kion_r"

val_schemes:
  - "time_split"

models:

  - report_file_name: training_obj
    cls: SASRecModel
    comment: _DenseAA-7-days+LiGR+SS_
    fixed_parameters:
      verbose: 1
      deterministic: True
      get_val_mask_func: src.models.transformers.trainer.get_val_mask_func_val_users_2048
      get_trainer_func: src.models.transformers.trainer.get_trainer_val_loss
      data_preparator_type: src.models.rl.objectives.dense_all_action.RewardedDenseAllActionDataPreparator
      transformer_layers_type: src.models.transformers.transformer_layers.ligr.LiGRLayers
      use_key_padding_mask: True
      dropout_rate: 0.1
      session_max_len: 50
      n_factors: 256
      n_blocks: 2
      n_heads: 2
      loss: sampled_softmax
      n_negatives: 256
      data_preparator_kwargs.targets_window_days: 7
    search_parameters:

  - report_file_name: training_obj
    cls: SASRecModel
    comment: _AllAction-14-days+LiGR+SS_
    fixed_parameters:
      verbose: 1
      deterministic: True
      get_val_mask_func: src.models.transformers.trainer.get_val_mask_func_val_users_2048
      get_trainer_func: src.models.transformers.trainer.get_trainer_val_loss
      data_preparator_type: src.models.rl.objectives.all_action.RewardedAllActionDataPreparator
      backbone_type: src.models.transformers.objective.all_action.AllActionTransformerTorchBackbone
      lightning_module_type: src.models.transformers.objective.all_action.AllActionLightningModule
      transformer_layers_type: src.models.transformers.transformer_layers.ligr.LiGRLayers
      use_key_padding_mask: True
      dropout_rate: 0.1
      session_max_len: 50
      n_factors: 256
      n_blocks: 2
      n_heads: 2
      loss: sampled_softmax
      n_negatives: 256
      data_preparator_kwargs.last_k_days: 14
    search_parameters:

  - report_file_name: training_obj
    cls: SASRecModel
    comment: _NextAction+LiGR+SS_
    fixed_parameters:
      verbose: 1
      deterministic: True
      get_val_mask_func: src.models.transformers.trainer.get_val_mask_func_val_users_2048
      get_trainer_func: src.models.transformers.trainer.get_trainer_val_loss
      data_preparator_type: src.models.rl.objectives.next_action.RewardedNextActionDataPreparator
      lightning_module_type: src.models.transformers.objective.next_action.NextActionLightningModule
      transformer_layers_type: src.models.transformers.transformer_layers.ligr.LiGRLayers
      use_key_padding_mask: True
      dropout_rate: 0.1
      session_max_len: 50
      n_factors: 256
      n_blocks: 2
      n_heads: 2
      loss: sampled_softmax
      n_negatives: 256
    search_parameters:

  - report_file_name: training_obj
    cls: BERT4RecModel
    comment: _BERT4Rec+LiGR+SS_
    fixed_parameters:
      verbose: 1
      deterministic: True
      get_val_mask_func: src.models.transformers.trainer.get_val_mask_func_val_users_2048
      get_trainer_func: src.models.transformers.trainer.get_trainer_val_loss
      data_preparator_type: src.models.rl.data_preparators.RewardedBERT4RecDataPreparator
      transformer_layers_type: src.models.transformers.transformer_layers.ligr.LiGRLayers
      use_key_padding_mask: True
      use_causal_attn: False
      dropout_rate: 0.1
      session_max_len: 50
      n_factors: 256
      n_blocks: 2
      n_heads: 2
      loss: sampled_softmax
      n_negatives: 256
    search_parameters:
